# Generated by Django 5.0.1 on 2024-01-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('desctiption', models.TextField()),
                ('price', models.TextField()),
                ('summary', models.TextField(default='wow it works')),
            ],
        ),
    ]
